proposal:
	xelatex thesis-proposal.tex
	bibtex thesis-proposal.aux
	xelatex thesis-proposal.tex
	xelatex thesis-proposal.tex
	rm -rf *.aux *.log *.out *.bbl *.blg
mini-proposal:
	markdown2pdf mini-proposal.md
